--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/theSpawn
build-by-default: true
branches:
- master
- development
projects:
  theSpawn:
    icon: "icon.png"
    path: ""
    php: 8.0
    libs:
      - src: "https://poggit.pmmp.io/ci/supercrafter333/FormAPI/libFormAPI"
        version: ^2.1