name: theSpawn
version: 0.4.0
api: 3.0.0
main: supercrafter333\theSpawn\theSpawn
mcpe-protocols:
  - 407
  - 408
  - 419
  - 422
author: supercrafter333

commands:
  setthespawn:
    description: §r§aSet the spawn for this world!
    permission: setthespawn.cmd
    aliases: ["addthespawn", "setspawn"]
  delthespawn:
    description: §r§aRemove the spawn of this world!
    permission: delthespawn.cmd
    aliases: ["deletethespawn", "removethespawn", "rmthespawn", "delspawn"]
  spawn:
    description: §r§9Teleport you to spawn of this world!
    aliases: ["tpthespawn"]
  setthehub:
    description: §r§aSet the hub!
    permission: setthehub.cmd
    aliases: ["addthehub", "setthelobby", "addthelobby", "sethub", "setlobby"]
  delthehub:
    description: §r§aRemove the hub spawnpoint!
    permission: delthehub.cmd
    aliases: ["rmthehub", "rmthelobby", "delthelobby", "delhub", "dellobby"]
  hub:
    description: §r§9Teleport you to hub!
    aliases: ["lobby", "thelobby", "thehub"]
  setalias:
    description: §r§aSet an alias for a world!
    aliases:
      - addalias
  removealias:
    description: §r§aRemove an alias!
    aliases:
      - rmalias

permissions:
  theSpawn.bypass:
    default: op
    children:
      theSpawn.setthespawn.cmd:
        default: op
      theSpawn.delthespawn.cmd:
        default: op
      theSpawn.setthehub.cmd:
        default: op
      theSpawn.delthehub.cmd:
        default: op
      theSpawn.setalias.cmd:
        default: op
      theSpawn.removealias.cmd:
        default: op