name: theSpawn
version: 1.8.4-PM5-dev
api: [4.4.0, 5.0.0]
main: supercrafter333\theSpawn\theSpawn
src-namespace-prefix: supercrafter333\theSpawn
author: supercrafter333

permissions:
  theSpawn.bypass:
    default: op
  theSpawn.setspawn.cmd:
    default: op
  theSpawn.delspawn.cmd:
    default: op
  theSpawn.sethub.cmd:
    default: op
  theSpawn.delhub.cmd:
    default: op
  theSpawn.setalias.cmd:
    default: op
  theSpawn.removealias.cmd:
    default: op
  theSpawn.setwarp.cmd:
    default: op
  theSpawn.delwarp.cmd:
    default: op
  theSpawn.sethome.cmd:
    default: true
  theSpawn.delhome.cmd:
    default: true
  theSpawn.home.cmd:
    default: true
  theSpawn.edithome.cmd:
    default: true
  theSpawn.warp.cmd:
    default: true
  theSpawn.editwarp.cmd:
    default: op
  theSpawn.tpa.cmd:
    default: true
  theSpawn.tpahere.cmd:
    default: true
  theSpawn.tpaccept.cmd:
    default: true
  theSpawn.tpdecline.cmd:
    default: true
  theSpawn.warp.admin: #teleport you to all warps with or without the permission for the warp
    default: op
  theSpawn.homes:
    default: op
  theSpawn.homes.unlimited:
    default: op
  theSpawn.back.cmd:
    default: true