name: theSpawn
version: 1.3.0-DEV
api: 3.0.0
main: supercrafter333\theSpawn\theSpawn
author: supercrafter333
mcpe-protocols:
  - 407
  - 408
  - 419
  - 422
  - 428
  - 431

permissions:
  theSpawn.sethome.cmd:
    default: true
  theSpawn.delhome.cmd:
    default: true
  theSpawn.home.cmd:
    default: true
  theSpawn.warp.cmd:
    default: true
  theSpawn.bypass:
    default: op
    children:
      theSpawn.setspawn.cmd:
        default: op
      theSpawn.delspawn.cmd:
        default: op
      theSpawn.sethub.cmd:
        default: op
      theSpawn.delhub.cmd:
        default: op
      theSpawn.setalias.cmd:
        default: op
      theSpawn.removealias.cmd:
        default: op
      theSpawn.setwarp.cmd:
        default: op
      theSpawn.delwarp.cmd:
        default: op