#hub server teleport
use-hub-server: "false"
hub-server-ip: "000.00.000.00" #if you use WaterdogPE, plese insert the server-name here
hub-server-port: "19132" #if you use WaterdogPE, plese set an empty string here (like: "")

#waterdog (not WDPE) teleport (hub server teleport must be enabled to enable this)
waterdog-hub-teleport: "false"
waterdog-servername: "name"

#random-(/multi-)hubs [true | false]
### Only available with deactivated hub servers
use-random-hubs: "false"

#aliases [true | false]
use-aliases: "true"

#homes [true | false]
use-homes: "true"

#warps [true | false]
use-warps: "true"

#hub teleport on Join [true | false]
hub-teleport-on-join: "false"


#don't change this
version: "1.3.2"

############################
##########theSpawn##########
############################
#Licensed under Apache License 2.0! Plugin by supercrafter333 inspirated by MSpawns from EvolSoft!
