#hub server teleport
use-hub-server: "false"
hub-server-ip: "000.00.000.00"
hub-server-port: "19132"

#waterdog teleport (hub server teleport must be enabled to enable this)
waterdog-hub-teleport: "false"
waterdog-servername: "name"

#aliases [true | false]
use-aliases: "true"

#homes [true | false]
use-homes: "true"



#don't change this
version: "1.0.0"

############################
##########theSpawn##########
############################
#Licensed under Apache License 2.0! Plugin by supercrafter333 inspirated by MSpawns from EvolSoft!