#hub server teleport
use-hub-server: "false"
hub-server-ip: "000.00.000.00" #if you use WaterdogPE, please insert the server-name here
hub-server-port: "19132" #if you use WaterdogPE, please set an empty string here (like: "")

#waterdog (not WDPE) teleport (hub server teleport must be enabled to enable this)
waterdog-hub-teleport: "false"
waterdog-servername: "name"

#random-(/multi-)hubs [true | false]
### Only available with deactivated hub servers
use-random-hubs: "false"

#aliases [true | false]
use-aliases: "true"

#homes [true | false]
use-homes: "true"

#warps [true | false]
use-warps: "true"

#TPAs [true | false]
use-tpas: "true"
tpa-time: 30 #seconds

#Spawn Teleport delay [true | false]
use-spawnDelay: "false"
spawn-delay-seconds: 3

#hub teleport on join [true | false]
hub-teleport-on-join: "true"

#hub teleport on death [true | false]
hub-teleport-on-death: "true"

#use Forms [true | false]
use-forms: "true"

#use max home permissions [true | false]
use-max-home-permissions: "false"

# /back command for  return to the point where you have died [true | false]
use-back-command: "true"
# maximum time in which the player can return to the point of death, setting it to "0" will make it possible for the player to use it whenever he wants
### IN MINUTES ###
back-time: 15

################
### Language ###
################
#
# Languages:
# -> 'en_BE' - British English
# -> 'ger_DE' - German
# -> 'es_ES' - Spanish
# -> 'fr_FR' - French
# -> 'CUSTOM' - Edit the messages yourself
#
# INFORMATION! -> Some languages can be outdated
#
# Chose you language here:
language: "en_BE"



####### BETA FEATURE #######
# check positions before teleport [true | false]
check-positions: "false"
####### BETA FEATURE #######




#DON'T CHANGE THIS!!
version: "1.8.4-dev"

############################
##########theSpawn##########
############################
#Licensed under Apache License 2.0! Plugin by supercrafter333 inspirated by MSpawns from EvolSoft!
